# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Fiee/Documents/GitHouse/Riscv-design/source/IPs/DRAM/DRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DRAM || ORIG_REF_NAME==DRAM} -quiet] -quiet
